services:
  nginx-react:
    image: smoluu/smolander.dev
    container_name: smolander-dev
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "82:80"
networks:
  default:
    external: false
    name: custom
# docker compose build
# docker compose up