services:
  nginx-react:
    container_name: ngixreact_smolander_dev
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "82:80"
networks:
  default:
    external: false
    name: custom
# docker compose build
# docker compose up